### user registration
POST http://localhost:4000/user-api/user
Content-Type: application/json

{
    "userType": "user",
    "username": "vivek",
    "password": "vivek",
    "email": "vivek@gmail.com"
}


### user login
POST http://localhost:4000/user-api/login
Content-Type: application/json

{
    "userType": "user",
    "username": "vivek",
    "password": "vivek",
    "email": "vivek@gmail.com"
}


###  get articles
GET http://localhost:4000/user-api/articles


### comment
POST http://localhost:4000/user-api/comment/1709439995
Content-Type: application/json

{
    "username": "vivek",
    "comment": "Amazing fantastic post"
}